name: Node Continuous Intergration

on:
    push:
        branches: ["**"]
        tags: ["**"]
        pull_request:
            branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build library
              run: pnpm build
            - name: Run Unit Tests
              run: pnpm test
            - name: Lint code
              run: pnpm lint
